//Problem 2: Even Fibonacci numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

var firstNum = 1;
var secondNum = 2;
var thirdNum = 3;
var sumOfNumbers = 2;

while (thirdNum <= 4000000) {

  if (thirdNum % 2 === 0) {
    sumOfNumbers = sumOfNumbers + thirdNum;
  }

  firstNum = secondNum;
  secondNum = thirdNum;
  thirdNum = firstNum + secondNum
}

console.log(sumOfNumbers);
